name: neurotrace
channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base>=4.2
  - r-data.table
  - r-ggplot2
  - r-matrix
  - r-optparse
  - r-yaml
  - r-pheatmap
  - r-igraph
  - r-reshape2
  - r-patchwork
  - python>=3.10
  - pandas
  - numpy
  - scipy
  - scikit-learn
